"""empty message

Revision ID: 139d93cb54ca
Revises: f00c50394a06
Create Date: 2024-01-30 21:26:18.163224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139d93cb54ca'
down_revision = 'f00c50394a06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('default', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_roles_default'), ['default'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_default'))
        batch_op.drop_column('default')
        batch_op.drop_column('permissions')

    # ### end Alembic commands ###
