"""empty message

Revision ID: 553dbc895ec8
Revises: 76f9af635e48
Create Date: 2024-01-27 13:00:25.871393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553dbc895ec8'
down_revision = '76f9af635e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('passwd_hash',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('passwd_hash',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
