"""empty message

Revision ID: 55b0c9b735dc
Revises: 2ce94649e812
Create Date: 2024-02-17 22:27:37.981734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b0c9b735dc'
down_revision = '2ce94649e812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_hash', sa.VARCHAR(length=32), nullable=True))

    # ### end Alembic commands ###
