"""empty message

Revision ID: f00c50394a06
Revises: 553dbc895ec8
Create Date: 2024-01-27 13:32:38.935586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f00c50394a06'
down_revision = '553dbc895ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))
        batch_op.alter_column('passwd_hash',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('passwd_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
